packages:
  - "packages/*"

minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade
strictDepBuilds: true
overrides:
  "semver@<7.0.0": "^7.8.5"
allowBuilds:
  esbuild: true
  lefthook: true
  workerd: true
